"""Framework-independent operations for building structured lessons."""

from teacher.interfaces import ChatModel
from teacher.models import (
    Chapter,
    ChapterOutline,
    Citation,
    Concept,
    ConceptDocumentSpan,
    ConceptIntent,
    ExplanationDepth,
    GlossaryEntry,
    GlossaryLink,
    Lesson,
    LessonMaterials,
    LessonOutline,
    ProgressionAxis,
    Reference,
    ReferenceDocument,
    ReferenceMaterial,
    ReferenceNote,
    ReferencePage,
    ReferenceSection,
    ReferenceSections,
    TimeSpan,
    Transcript,
    TranscriptSegment,
)
from teacher.operations import (
    ChapterWriter,
    GlossaryWriter,
    OutlineWriter,
    ReferenceReader,
    TranscriptRevision,
)
from teacher.outputs import (
    ExportError,
    ExportFormat,
    ExportMetadata,
    MarkdownExporter,
    PandocExporter,
)

__all__ = [
    "ChatModel",
    "Transcript",
    "TranscriptSegment",
    "TranscriptRevision",
    "ReferenceDocument",
    "ReferenceReader",
    "ReferenceMaterial",
    "Reference",
    "ReferencePage",
    "ReferenceSection",
    "ReferenceSections",
    "ReferenceNote",
    "LessonMaterials",
    "OutlineWriter",
    "LessonOutline",
    "ChapterOutline",
    "Concept",
    "ConceptDocumentSpan",
    "ConceptIntent",
    "ProgressionAxis",
    "ExplanationDepth",
    "ChapterWriter",
    "Chapter",
    "GlossaryWriter",
    "GlossaryEntry",
    "GlossaryLink",
    "Citation",
    "TimeSpan",
    "Lesson",
    "ExportError",
    "ExportFormat",
    "ExportMetadata",
    "MarkdownExporter",
    "PandocExporter",
]
